
# 仪器列表
# 格式：
#     - # 一个仪器
#         type: 仪器类型名称，需要用 @Instrument.register(id:str) 在仪器类前注册
#         id: 仪器自定义 id，不可重复，可选，便于保存和迁移扫描设置
#         address: 地址，可以是一个地址列表，例如本源的 DAC
#         config: config 文件夹中的配置文件路径

# 类型: list
# 默认值: []
instruments: 
  - 
    type: counter
    id: Counter
    address: ''
    config: 'instruments/counter.yaml'

# 多线程控制数量，0 时禁用
#             
# 类型: int
# 范围: -inf ~ 64
# 默认值: 16
max_threads: 16
