# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Documents\Proj\Axolotl\axolotl\gui\assets\channel_ctrl.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChannelCtrl(object):
    def setupUi(self, ChannelCtrl):
        ChannelCtrl.setObjectName("ChannelCtrl")
        ChannelCtrl.resize(1104, 415)
        self.verticalLayout = QtWidgets.QVBoxLayout(ChannelCtrl)
        self.verticalLayout.setObjectName("verticalLayout")
        self.channel_layout = QtWidgets.QGridLayout()
        self.channel_layout.setObjectName("channel_layout")
        self.verticalLayout.addLayout(self.channel_layout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.set_button = QtWidgets.QPushButton(ChannelCtrl)
        self.set_button.setObjectName("set_button")
        self.horizontalLayout_3.addWidget(self.set_button)
        self.refresh_button = QtWidgets.QPushButton(ChannelCtrl)
        self.refresh_button.setObjectName("refresh_button")
        self.horizontalLayout_3.addWidget(self.refresh_button)
        self.auto_refresh_checkbox = QtWidgets.QCheckBox(ChannelCtrl)
        self.auto_refresh_checkbox.setObjectName("auto_refresh_checkbox")
        self.horizontalLayout_3.addWidget(self.auto_refresh_checkbox)
        self.label = QtWidgets.QLabel(ChannelCtrl)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.refresh_interval_spinbox = QtWidgets.QDoubleSpinBox(ChannelCtrl)
        self.refresh_interval_spinbox.setDecimals(1)
        self.refresh_interval_spinbox.setMinimum(0.5)
        self.refresh_interval_spinbox.setMaximum(100.0)
        self.refresh_interval_spinbox.setObjectName("refresh_interval_spinbox")
        self.horizontalLayout_3.addWidget(self.refresh_interval_spinbox)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 15)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(ChannelCtrl)
        QtCore.QMetaObject.connectSlotsByName(ChannelCtrl)

    def retranslateUi(self, ChannelCtrl):
        _translate = QtCore.QCoreApplication.translate
        ChannelCtrl.setWindowTitle(_translate("ChannelCtrl", "GroupBox"))
        ChannelCtrl.setTitle(_translate("ChannelCtrl", "通道设置"))
        self.set_button.setText(_translate("ChannelCtrl", "设置"))
        self.refresh_button.setText(_translate("ChannelCtrl", "刷新"))
        self.auto_refresh_checkbox.setText(_translate("ChannelCtrl", "自动刷新"))
        self.label.setText(_translate("ChannelCtrl", "刷新周期：(s)"))
